name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Adjust this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version
      - name: Authenticate GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken= 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" > ~/.npmrc


          

      - name: Install dependencies
        run: npm install

      - name: Build applications
        run: |
          npx nx build app-1 --prod
          npx nx build app-2 --prod
          npx nx build app-3 --prod

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: nfp_Ur4TdsEK3BXJL7izx8UaQLJotCzdExUn7658
          NETLIFY_SITE_ID: ojjc61XM-WfNtlsXPMaMFRxqLBFyo2GgP0MaumLKLZc

        run: |
          npx netlify-cli deploy --prod --dir=dist/apps/app-1
          npx netlify-cli deploy --prod --dir=dist/apps/app-2
          npx netlify-cli deploy --prod --dir=dist/apps/app-3
