name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Adjust this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Authenticate GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken= 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" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build applications
        run: |
          npx nx build app-1 --prod
          npx nx build app-2 --prod
          npx nx build app-3 --prod

      - name: Deploy app 1 to Netlify (Replace with your site ID)
        env:
          NETLIFY_AUTH_TOKEN: nfp_Ur4TdsEK3BXJL7izx8UaQLJotCzdExUn7658
          NETLIFY_SITE_ID: 3750be94-568c-42d9-ae4d-3392f3d7d1b6  # Replace with your app 1 site ID
        run: npx netlify-cli deploy --prod --dir=dist/apps/app-1

      - name: Deploy app 2 to Netlify (Replace with your site ID)
        env:
          NETLIFY_AUTH_TOKEN: nfp_Ur4TdsEK3BXJL7izx8UaQLJotCzdExUn7658
          NETLIFY_SITE_ID: your_app_2_site_id  # Replace with your app 2 site ID
        run: npx netlify-cli deploy --prod --dir=dist/apps/app-2

      # Repeat for app 3 with its specific site ID